package com.liferay.github.automator.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.github.automator.model.GHAutomatorTask;
import com.liferay.github.automator.service.GHAutomatorTaskLocalServiceUtil;

/**
 * The extended model base implementation for the GHAutomatorTask service. Represents a row in the &quot;GHAutomatorTask&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link GHAutomatorTaskImpl}.
 * </p>
 *
 * @author Sergio González
 * @see GHAutomatorTaskImpl
 * @see GHAutomatorTask
 * @generated
 */
@ProviderType
public abstract class GHAutomatorTaskBaseImpl extends GHAutomatorTaskModelImpl
	implements GHAutomatorTask {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a g h automator task model instance should use the {@link GHAutomatorTask} interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			GHAutomatorTaskLocalServiceUtil.addGHAutomatorTask(this);
		}
		else {
			GHAutomatorTaskLocalServiceUtil.updateGHAutomatorTask(this);
		}
	}
}