/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.github.automator.service.base;

import aQute.bnd.annotation.ProviderType;

import com.liferay.github.automator.model.GHAutomatorRepository;
import com.liferay.github.automator.service.GHAutomatorRepositoryLocalService;
import com.liferay.github.automator.service.persistence.GHAutomatorRepositoryPersistence;
import com.liferay.github.automator.service.persistence.GHAutomatorTaskPersistence;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalServiceRegistry;
import com.liferay.portal.kernel.service.persistence.ClassNamePersistence;
import com.liferay.portal.kernel.service.persistence.UserPersistence;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.spring.extender.service.ServiceReference;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the g h automator repository local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.github.automator.service.impl.GHAutomatorRepositoryLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.liferay.github.automator.service.impl.GHAutomatorRepositoryLocalServiceImpl
 * @see com.liferay.github.automator.service.GHAutomatorRepositoryLocalServiceUtil
 * @generated
 */
@ProviderType
public abstract class GHAutomatorRepositoryLocalServiceBaseImpl
	extends BaseLocalServiceImpl implements GHAutomatorRepositoryLocalService,
		IdentifiableOSGiService {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.liferay.github.automator.service.GHAutomatorRepositoryLocalServiceUtil} to access the g h automator repository local service.
	 */

	/**
	 * Adds the g h automator repository to the database. Also notifies the appropriate model listeners.
	 *
	 * @param ghAutomatorRepository the g h automator repository
	 * @return the g h automator repository that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public GHAutomatorRepository addGHAutomatorRepository(
		GHAutomatorRepository ghAutomatorRepository) {
		ghAutomatorRepository.setNew(true);

		return ghAutomatorRepositoryPersistence.update(ghAutomatorRepository);
	}

	/**
	 * Creates a new g h automator repository with the primary key. Does not add the g h automator repository to the database.
	 *
	 * @param ghAutomatorRepositoryId the primary key for the new g h automator repository
	 * @return the new g h automator repository
	 */
	@Override
	public GHAutomatorRepository createGHAutomatorRepository(
		long ghAutomatorRepositoryId) {
		return ghAutomatorRepositoryPersistence.create(ghAutomatorRepositoryId);
	}

	/**
	 * Deletes the g h automator repository with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param ghAutomatorRepositoryId the primary key of the g h automator repository
	 * @return the g h automator repository that was removed
	 * @throws PortalException if a g h automator repository with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public GHAutomatorRepository deleteGHAutomatorRepository(
		long ghAutomatorRepositoryId) throws PortalException {
		return ghAutomatorRepositoryPersistence.remove(ghAutomatorRepositoryId);
	}

	/**
	 * Deletes the g h automator repository from the database. Also notifies the appropriate model listeners.
	 *
	 * @param ghAutomatorRepository the g h automator repository
	 * @return the g h automator repository that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public GHAutomatorRepository deleteGHAutomatorRepository(
		GHAutomatorRepository ghAutomatorRepository) {
		return ghAutomatorRepositoryPersistence.remove(ghAutomatorRepository);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(GHAutomatorRepository.class,
			clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return ghAutomatorRepositoryPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.liferay.github.automator.model.impl.GHAutomatorRepositoryModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery, int start,
		int end) {
		return ghAutomatorRepositoryPersistence.findWithDynamicQuery(dynamicQuery,
			start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.liferay.github.automator.model.impl.GHAutomatorRepositoryModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery, int start,
		int end, OrderByComparator<T> orderByComparator) {
		return ghAutomatorRepositoryPersistence.findWithDynamicQuery(dynamicQuery,
			start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return ghAutomatorRepositoryPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery,
		Projection projection) {
		return ghAutomatorRepositoryPersistence.countWithDynamicQuery(dynamicQuery,
			projection);
	}

	@Override
	public GHAutomatorRepository fetchGHAutomatorRepository(
		long ghAutomatorRepositoryId) {
		return ghAutomatorRepositoryPersistence.fetchByPrimaryKey(ghAutomatorRepositoryId);
	}

	/**
	 * Returns the g h automator repository with the primary key.
	 *
	 * @param ghAutomatorRepositoryId the primary key of the g h automator repository
	 * @return the g h automator repository
	 * @throws PortalException if a g h automator repository with the primary key could not be found
	 */
	@Override
	public GHAutomatorRepository getGHAutomatorRepository(
		long ghAutomatorRepositoryId) throws PortalException {
		return ghAutomatorRepositoryPersistence.findByPrimaryKey(ghAutomatorRepositoryId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery = new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(ghAutomatorRepositoryLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(GHAutomatorRepository.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"ghAutomatorRepositoryId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery getIndexableActionableDynamicQuery() {
		IndexableActionableDynamicQuery indexableActionableDynamicQuery = new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(ghAutomatorRepositoryLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(GHAutomatorRepository.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"ghAutomatorRepositoryId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {
		actionableDynamicQuery.setBaseLocalService(ghAutomatorRepositoryLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(GHAutomatorRepository.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"ghAutomatorRepositoryId");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {
		return ghAutomatorRepositoryLocalService.deleteGHAutomatorRepository((GHAutomatorRepository)persistedModel);
	}

	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {
		return ghAutomatorRepositoryPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the g h automator repositories.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.liferay.github.automator.model.impl.GHAutomatorRepositoryModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param start the lower bound of the range of g h automator repositories
	 * @param end the upper bound of the range of g h automator repositories (not inclusive)
	 * @return the range of g h automator repositories
	 */
	@Override
	public List<GHAutomatorRepository> getGHAutomatorRepositories(int start,
		int end) {
		return ghAutomatorRepositoryPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of g h automator repositories.
	 *
	 * @return the number of g h automator repositories
	 */
	@Override
	public int getGHAutomatorRepositoriesCount() {
		return ghAutomatorRepositoryPersistence.countAll();
	}

	/**
	 * Updates the g h automator repository in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param ghAutomatorRepository the g h automator repository
	 * @return the g h automator repository that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public GHAutomatorRepository updateGHAutomatorRepository(
		GHAutomatorRepository ghAutomatorRepository) {
		return ghAutomatorRepositoryPersistence.update(ghAutomatorRepository);
	}

	/**
	 * Returns the g h automator repository local service.
	 *
	 * @return the g h automator repository local service
	 */
	public GHAutomatorRepositoryLocalService getGHAutomatorRepositoryLocalService() {
		return ghAutomatorRepositoryLocalService;
	}

	/**
	 * Sets the g h automator repository local service.
	 *
	 * @param ghAutomatorRepositoryLocalService the g h automator repository local service
	 */
	public void setGHAutomatorRepositoryLocalService(
		GHAutomatorRepositoryLocalService ghAutomatorRepositoryLocalService) {
		this.ghAutomatorRepositoryLocalService = ghAutomatorRepositoryLocalService;
	}

	/**
	 * Returns the g h automator repository persistence.
	 *
	 * @return the g h automator repository persistence
	 */
	public GHAutomatorRepositoryPersistence getGHAutomatorRepositoryPersistence() {
		return ghAutomatorRepositoryPersistence;
	}

	/**
	 * Sets the g h automator repository persistence.
	 *
	 * @param ghAutomatorRepositoryPersistence the g h automator repository persistence
	 */
	public void setGHAutomatorRepositoryPersistence(
		GHAutomatorRepositoryPersistence ghAutomatorRepositoryPersistence) {
		this.ghAutomatorRepositoryPersistence = ghAutomatorRepositoryPersistence;
	}

	/**
	 * Returns the g h automator task local service.
	 *
	 * @return the g h automator task local service
	 */
	public com.liferay.github.automator.service.GHAutomatorTaskLocalService getGHAutomatorTaskLocalService() {
		return ghAutomatorTaskLocalService;
	}

	/**
	 * Sets the g h automator task local service.
	 *
	 * @param ghAutomatorTaskLocalService the g h automator task local service
	 */
	public void setGHAutomatorTaskLocalService(
		com.liferay.github.automator.service.GHAutomatorTaskLocalService ghAutomatorTaskLocalService) {
		this.ghAutomatorTaskLocalService = ghAutomatorTaskLocalService;
	}

	/**
	 * Returns the g h automator task persistence.
	 *
	 * @return the g h automator task persistence
	 */
	public GHAutomatorTaskPersistence getGHAutomatorTaskPersistence() {
		return ghAutomatorTaskPersistence;
	}

	/**
	 * Sets the g h automator task persistence.
	 *
	 * @param ghAutomatorTaskPersistence the g h automator task persistence
	 */
	public void setGHAutomatorTaskPersistence(
		GHAutomatorTaskPersistence ghAutomatorTaskPersistence) {
		this.ghAutomatorTaskPersistence = ghAutomatorTaskPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the class name local service.
	 *
	 * @return the class name local service
	 */
	public com.liferay.portal.kernel.service.ClassNameLocalService getClassNameLocalService() {
		return classNameLocalService;
	}

	/**
	 * Sets the class name local service.
	 *
	 * @param classNameLocalService the class name local service
	 */
	public void setClassNameLocalService(
		com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService) {
		this.classNameLocalService = classNameLocalService;
	}

	/**
	 * Returns the class name persistence.
	 *
	 * @return the class name persistence
	 */
	public ClassNamePersistence getClassNamePersistence() {
		return classNamePersistence;
	}

	/**
	 * Sets the class name persistence.
	 *
	 * @param classNamePersistence the class name persistence
	 */
	public void setClassNamePersistence(
		ClassNamePersistence classNamePersistence) {
		this.classNamePersistence = classNamePersistence;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.kernel.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.kernel.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.kernel.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		persistedModelLocalServiceRegistry.register("com.liferay.github.automator.model.GHAutomatorRepository",
			ghAutomatorRepositoryLocalService);
	}

	public void destroy() {
		persistedModelLocalServiceRegistry.unregister(
			"com.liferay.github.automator.model.GHAutomatorRepository");
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return GHAutomatorRepositoryLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return GHAutomatorRepository.class;
	}

	protected String getModelClassName() {
		return GHAutomatorRepository.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = ghAutomatorRepositoryPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = GHAutomatorRepositoryLocalService.class)
	protected GHAutomatorRepositoryLocalService ghAutomatorRepositoryLocalService;
	@BeanReference(type = GHAutomatorRepositoryPersistence.class)
	protected GHAutomatorRepositoryPersistence ghAutomatorRepositoryPersistence;
	@BeanReference(type = com.liferay.github.automator.service.GHAutomatorTaskLocalService.class)
	protected com.liferay.github.automator.service.GHAutomatorTaskLocalService ghAutomatorTaskLocalService;
	@BeanReference(type = GHAutomatorTaskPersistence.class)
	protected GHAutomatorTaskPersistence ghAutomatorTaskPersistence;
	@ServiceReference(type = com.liferay.counter.kernel.service.CounterLocalService.class)
	protected com.liferay.counter.kernel.service.CounterLocalService counterLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.ClassNameLocalService.class)
	protected com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService;
	@ServiceReference(type = ClassNamePersistence.class)
	protected ClassNamePersistence classNamePersistence;
	@ServiceReference(type = com.liferay.portal.kernel.service.ResourceLocalService.class)
	protected com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.UserLocalService.class)
	protected com.liferay.portal.kernel.service.UserLocalService userLocalService;
	@ServiceReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	@ServiceReference(type = PersistedModelLocalServiceRegistry.class)
	protected PersistedModelLocalServiceRegistry persistedModelLocalServiceRegistry;
}